apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: students-svc
  name: students-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students-svc
  template:
    metadata:
      labels:
        app: students-svc
    spec:
      containers:
        - name: students-svc
          image: roelvandegrint.azurecr.io/study-buddy/students-svc:latest
      imagePullSecrets:
        - name: roelvandegrint.azurecr.io
