apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: students-svc
  name: students-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students-svc
  template:
    metadata:
      labels:
        app: students-svc
    spec:
      containers:
        - name: students-svc
          image: image:0.0.1
